parameters:
  omnipay.class: ColinODell\OmnipayBundle\Service\Omnipay

services:
  omnipay:
    class: "%omnipay.class%"
    arguments:
      - "@omnipay.factory"

  omnipay.factory:
    class: Omnipay\Common\GatewayFactory
    public: false
